version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    groups:
      go-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: weekly
    groups:
      web-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: "/plugin/opencode"
    schedule:
      interval: weekly
    groups:
      opencode-plugin-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: weekly
    groups:
      docker-server-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: "/web"
    schedule:
      interval: weekly
    groups:
      docker-web-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions-minor-patch:
        update-types:
          - minor
          - patch
