package domain

import "time"

// SyncBatch is the transport-neutral replication unit. SyncID is generated by
// the originating client and remains stable across retries and devices.
type SyncBatch struct {
	Sessions     []SyncSession     `json:"sessions,omitempty"`
	Observations []SyncObservation `json:"observations,omitempty"`
	Prompts      []SyncPrompt      `json:"prompts,omitempty"`
	Edges        []SyncEdge        `json:"edges,omitempty"`
}

type SyncSession struct {
	SyncID    string     `json:"sync_id"`
	Project   string     `json:"project"`
	Directory string     `json:"directory,omitempty"`
	StartedAt time.Time  `json:"started_at"`
	EndedAt   *time.Time `json:"ended_at,omitempty"`
	Summary   string     `json:"summary,omitempty"`
	UpdatedAt time.Time  `json:"updated_at"`
	Deleted   bool       `json:"deleted,omitempty"`
}

type SyncObservation struct {
	SyncID        string    `json:"sync_id"`
	SessionSyncID string    `json:"session_sync_id"`
	Title         string    `json:"title"`
	Content       string    `json:"content"`
	Type          string    `json:"type"`
	Project       string    `json:"project"`
	Scope         string    `json:"scope"`
	TopicKey      string    `json:"topic_key,omitempty"`
	Confidence    float64   `json:"confidence"`
	Source        string    `json:"source"`
	Tags          []string  `json:"tags,omitempty"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	Deleted       bool      `json:"deleted,omitempty"`
}

type SyncPrompt struct {
	SyncID        string    `json:"sync_id"`
	SessionSyncID string    `json:"session_sync_id"`
	Content       string    `json:"content"`
	Project       string    `json:"project"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	Deleted       bool      `json:"deleted,omitempty"`
}

type SyncEdge struct {
	SyncID     string     `json:"sync_id"`
	FromSyncID string     `json:"from_sync_id"`
	ToSyncID   string     `json:"to_sync_id"`
	Relation   string     `json:"relation_type"`
	Weight     float64    `json:"weight"`
	Confidence float64    `json:"confidence"`
	Source     string     `json:"source,omitempty"`
	Reasoning  string     `json:"reasoning,omitempty"`
	ValidFrom  *time.Time `json:"valid_from,omitempty"`
	ValidUntil *time.Time `json:"valid_until,omitempty"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	Deleted    bool       `json:"deleted,omitempty"`
}

type SyncPage struct {
	SyncBatch
	Cursor  int64 `json:"cursor"`
	HasMore bool  `json:"has_more"`
}

type SyncResult struct {
	Accepted int `json:"accepted"`
}
